services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key-change-in-production
    restart: unless-stopped
    # Ограничения для 1 ядра
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 512M
        reservations:
          memory: 256M

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    # Ограничения для nginx
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          memory: 64M
